// Code generated by download. DO NOT EDIT.

package iso20022_seev_001_001_08

import (
	"bytes"
	"encoding/xml"
	"time"
)

type ActiveOrHistoricCurrencyAnd13DecimalAmount struct {
	Value float64                      `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveOrHistoricCurrencyCode string

// May be one of WQPS, RSPS, AIPS
type AdditionalRight1Code string

type AdditionalRightCode1Choice struct {
	Cd    AdditionalRight1Code    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Cd,omitempty"`
	Prtry GenericIdentification13 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Prtry,omitempty"`
}

type AdditionalRightThreshold1Choice struct {
	AddtlRghtThrshld     Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlRghtThrshld,omitempty"`
	AddtlRghtThrshldPctg float64   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlRghtThrshldPctg,omitempty"`
}

type AdditionalRights3 struct {
	AddtlRght          AdditionalRightCode1Choice      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlRght"`
	AddtlRghtInfURLAdr Max2048Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlRghtInfURLAdr,omitempty"`
	AddtlRghtDdln      DateFormat58Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlRghtDdln,omitempty"`
	AddtlRghtMktDdln   DateFormat58Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlRghtMktDdln,omitempty"`
	AddtlRghtThrshld   AdditionalRightThreshold1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlRghtThrshld,omitempty"`
}

// May be one of ADDR, PBOX, HOME, BIZZ, MLTO, DLVY
type AddressType2Code string

// May be one of PRIN, SUBA
type AgentRole1Code string

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

type Attendance2 struct {
	AdmssnConds []AttendanceAdmissionConditions2 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AdmssnConds,omitempty"`
	ConfInf     Max350Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 ConfInf,omitempty"`
	ConfDdln    DateFormat58Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 ConfDdln,omitempty"`
	ConfMktDdln DateFormat58Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 ConfMktDdln,omitempty"`
}

type AttendanceAdmissionConditions2 struct {
	Cd       AttendanceAdmissionConditions2Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Cd"`
	AddtlInf Max350Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlInf,omitempty"`
}

// May be one of MASH, MASL, MAPO, MAAL, MALR, MAHI, MATK, MADS, MANP
type AttendanceAdmissionConditions2Code string

type CommunicationAddress11 struct {
	EmailAdr Max256Text  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EmailAdr,omitempty"`
	URLAdr   Max2048Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 URLAdr,omitempty"`
}

type ContactIdentification1 struct {
	Nm       Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Nm"`
	NmPrfx   NamePrefix1Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NmPrfx,omitempty"`
	GvnNm    Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 GvnNm,omitempty"`
	Role     Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Role,omitempty"`
	PhneNb   PhoneNumber     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PhneNb,omitempty"`
	FaxNb    PhoneNumber     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 FaxNb,omitempty"`
	EmailAdr Max256Text      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EmailAdr,omitempty"`
}

type CorporateEventNarrative3 struct {
	Dsclmr []LanguageSpecifiedNarrative1 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Dsclmr,omitempty"`
}

// Must match the pattern [A-Z]{2,2}
type CountryCode string

type DateAndDateTime2Choice struct {
	Dt   ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Dt,omitempty"`
	DtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 DtTm,omitempty"`
}

type DateAndPlaceOfBirth2 struct {
	BirthDt     ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 BirthDt"`
	PrvcOfBirth Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrvcOfBirth,omitempty"`
	CityOfBirth Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 CityOfBirth,omitempty"`
	CtryOfBirth CountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 CtryOfBirth,omitempty"`
}

type DateFormat1 struct {
	Dt   DateFormat3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Dt"`
	DtMd DateMode1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 DtMd,omitempty"`
}

type DateFormat3Choice struct {
	Dt   ISODate       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Dt,omitempty"`
	DtCd DateType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 DtCd,omitempty"`
}

type DateFormat58Choice struct {
	DtOrDtTm DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 DtOrDtTm,omitempty"`
	DtCd     DateType1Code          `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 DtCd,omitempty"`
}

// May be one of BODY, EODY
type DateMode1Code string

// May be one of UKWN
type DateType1Code string

type Document struct {
	MtgNtfctn MeetingNotificationV08 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 MtgNtfctn"`
}

type EligiblePosition9 struct {
	AcctId    Max35Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AcctId"`
	AcctOwnr  PartyIdentification231Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AcctOwnr,omitempty"`
	HldgBal   []HoldingBalance9              `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 HldgBal,omitempty"`
	RghtsHldr []PartyIdentification233Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 RghtsHldr,omitempty"`
}

type Entitlement1Choice struct {
	EntitlmntRatio float64   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EntitlmntRatio,omitempty"`
	EntitlmntDesc  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EntitlmntDesc,omitempty"`
}

// May be one of COMP, INCO
type EventCompletenessStatus1Code string

// May be one of CONF, UCON
type EventConfirmationStatus1Code string

type EventStatus1 struct {
	EvtCmpltnsSts EventCompletenessStatus1Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EvtCmpltnsSts"`
	EvtConfSts    EventConfirmationStatus1Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EvtConfSts"`
}

// Must match the pattern [a-zA-Z0-9]{4}
type Exact4AlphaNumericText string

// May be no more than 4 items long
type ExternalFinancialInstrumentIdentificationType1Code string

type FinancialInstrumentQuantity18Choice struct {
	Unit    float64 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Unit,omitempty"`
	FaceAmt float64 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 FaceAmt,omitempty"`
}

type GenericIdentification13 struct {
	Id      Max4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id"`
	SchmeNm Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 SchmeNm,omitempty"`
	Issr    Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Issr"`
}

type GenericIdentification30 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id"`
	Issr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Issr"`
	SchmeNm Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 SchmeNm,omitempty"`
}

type GenericIdentification36 struct {
	Id      Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id"`
	Issr    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Issr"`
	SchmeNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 SchmeNm,omitempty"`
}

type GenericIdentification78 struct {
	Tp GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Tp"`
	Id Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id,omitempty"`
}

type HoldingBalance9 struct {
	Bal      FinancialInstrumentQuantity18Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Bal"`
	BalTp    SecuritiesEntryType2Code            `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 BalTp"`
	SfkpgPlc SafekeepingPlaceFormat28Choice      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 SfkpgPlc,omitempty"`
	Dt       ISODate                             `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Dt,omitempty"`
}

// Must match the pattern [A-Z]{2,2}[A-Z0-9]{9,9}[0-9]{1,1}
type ISINOct2015Identifier string

// Must match the pattern [a-z]{2,2}
type ISO2ALanguageCode string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

type IdentificationSource3Choice struct {
	Cd    ExternalFinancialInstrumentIdentificationType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Cd,omitempty"`
	Prtry Max35Text                                          `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Prtry,omitempty"`
}

type IdentificationType45Choice struct {
	Cd    TypeOfIdentification4Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Cd,omitempty"`
	Prtry GenericIdentification30   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Prtry,omitempty"`
}

type IncentivePremium5 struct {
	Desc  Max350Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Desc,omitempty"`
	Amt   PriceRateOrAmount3Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Amt"`
	Tp    IncentivePremiumType2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Tp"`
	PmtDt DateFormat3Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PmtDt,omitempty"`
}

type IncentivePremiumType2Choice struct {
	PerScty    float64                `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PerScty,omitempty"`
	PerVote    []VoteTypeAndQuantity1 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PerVote,omitempty"`
	PerAttndee bool                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PerAttndee,omitempty"`
}

type IndividualPerson43 struct {
	PrssgndPrxy PartyIdentification232Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrssgndPrxy,omitempty"`
	EmplngPty   PartyIdentification129Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EmplngPty,omitempty"`
}

type IssuerAgent3 struct {
	Id   PartyIdentification129Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id"`
	Role AgentRole1Code               `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Role,omitempty"`
}

type IssuerInformation3 struct {
	Id     PartyIdentification129Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id"`
	URLAdr Max2048Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 URLAdr,omitempty"`
}

type ItemDescription1 struct {
	Lang ISO2ALanguageCode `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Lang"`
	Titl Max350Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Titl,omitempty"`
	Desc Max1025Text       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Desc,omitempty"`
}

// Must match the pattern [A-Z0-9]{18,18}[0-9]{2,2}
type LEIIdentifier string

type LanguageSpecifiedNarrative1 struct {
	Lang     ISO2ALanguageCode `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Lang"`
	AddtlInf Max8000Text       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlInf"`
}

type LocationFormat1Choice struct {
	Adr    PostalAddress1 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Adr,omitempty"`
	LctnCd PlaceType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 LctnCd,omitempty"`
}

// Must match the pattern [A-Z0-9]{4,4}
type MICIdentifier string

// May be no more than 1025 items long
type Max1025Text string

// May be no more than 140 items long
type Max140Text string

// May be no more than 16 items long
type Max16Text string

// May be no more than 2048 items long
type Max2048Text string

// May be no more than 256 items long
type Max256Text string

// May be no more than 350 items long
type Max350Text string

// May be no more than 35 items long
type Max35Text string

// Must match the pattern [a-zA-Z0-9]{1,4}
type Max4AlphaNumericText string

// May be no more than 50 items long
type Max50Text string

// May be no more than 70 items long
type Max70Text string

// May be no more than 8000 items long
type Max8000Text string

type Meeting6 struct {
	DtAndTm  DateFormat58Choice      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 DtAndTm"`
	DtSts    MeetingDateStatus2Code  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 DtSts,omitempty"`
	QrmReqrd bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 QrmReqrd,omitempty"`
	Lctn     []LocationFormat1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Lctn"`
	QrmQty   QuorumQuantity1Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 QrmQty,omitempty"`
	URLAdr   Max2048Text             `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 URLAdr,omitempty"`
}

type MeetingContactPerson3 struct {
	CtctPrsn   ContactIdentification1       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 CtctPrsn,omitempty"`
	EmplngPty  PartyIdentification129Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EmplngPty,omitempty"`
	PlcOfListg MICIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PlcOfListg,omitempty"`
}

// May be one of CNFR, TNTA
type MeetingDateStatus2Code string

type MeetingEventReference1 struct {
	EvtId MeetingEventReference1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EvtId"`
	LkgTp ProcessingPosition3Code      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 LkgTp,omitempty"`
}

type MeetingEventReference1Choice struct {
	LkdIssrMtgId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 LkdIssrMtgId,omitempty"`
	LkdMtgId     Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 LkdMtgId,omitempty"`
}

type MeetingNotice6 struct {
	MtgId                 Max35Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 MtgId"`
	IssrMtgId             Max35Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 IssrMtgId,omitempty"`
	Tp                    MeetingType4Code                    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Tp"`
	Clssfctn              MeetingTypeClassification2Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Clssfctn,omitempty"`
	AnncmntDt             DateAndDateTime2Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AnncmntDt,omitempty"`
	OneManOneVoteInd      bool                                `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 OneManOneVoteInd,omitempty"`
	Prtcptn               []ParticipationMethod1              `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Prtcptn,omitempty"`
	Attndnc               Attendance2                         `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Attndnc,omitempty"`
	AddtlDcmnttnURLAdr    []Max2048Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlDcmnttnURLAdr,omitempty"`
	AddtlPrcdrDtls        []AdditionalRights3                 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlPrcdrDtls,omitempty"`
	TtlNbOfSctiesOutsdng  FinancialInstrumentQuantity18Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 TtlNbOfSctiesOutsdng,omitempty"`
	TtlNbOfVtngRghts      float64                             `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 TtlNbOfVtngRghts,omitempty"`
	PrxyAppntmntNtfctnAdr PostalAddress1                      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrxyAppntmntNtfctnAdr,omitempty"`
	PrxyChc               Proxy4Choice                        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrxyChc,omitempty"`
	CtctPrsnDtls          []MeetingContactPerson3             `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 CtctPrsnDtls,omitempty"`
	RsltPblctnDt          DateFormat3Choice                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 RsltPblctnDt,omitempty"`
	SctiesBlckgPrdEndDt   ISODateTime                         `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 SctiesBlckgPrdEndDt,omitempty"`
	EntitlmntFxgDt        DateFormat1                         `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EntitlmntFxgDt,omitempty"`
	RegnSctiesDdln        DateFormat58Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 RegnSctiesDdln,omitempty"`
	RegnSctiesMktDdln     DateFormat58Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 RegnSctiesMktDdln,omitempty"`
}

type MeetingNotificationV08 struct {
	NtfctnGnlInf      NotificationGeneralInformation2 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NtfctnGnlInf"`
	NtfctnUpd         NotificationUpdate2             `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NtfctnUpd,omitempty"`
	EvtsLkg           []MeetingEventReference1        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EvtsLkg,omitempty"`
	Mtg               MeetingNotice6                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Mtg"`
	MtgDtls           []Meeting6                      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 MtgDtls"`
	Issr              IssuerInformation3              `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Issr"`
	IssrAgt           []IssuerAgent3                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 IssrAgt,omitempty"`
	Scty              []SecurityPosition12            `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Scty"`
	Rsltn             []Resolution5                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Rsltn,omitempty"`
	Vote              VoteParameters6                 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Vote,omitempty"`
	PwrOfAttnyRqrmnts PowerOfAttorneyRequirements4    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PwrOfAttnyRqrmnts,omitempty"`
	AddtlInf          CorporateEventNarrative3        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlInf,omitempty"`
	SplmtryData       []SupplementaryData1            `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 SplmtryData,omitempty"`
}

// May be one of XMET, GMET, MIXD, SPCL, BMET, CMET
type MeetingType4Code string

type MeetingTypeClassification2Choice struct {
	Cd    MeetingTypeClassification2Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Cd,omitempty"`
	Prtry GenericIdentification13        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Prtry,omitempty"`
}

// May be one of AMET, CLAS, ISSU, OMET, VRHI
type MeetingTypeClassification2Code string

type NameAndAddress5 struct {
	Nm  Max350Text     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Nm"`
	Adr PostalAddress1 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Adr,omitempty"`
}

// May be one of DOCT, MIST, MISS, MADM
type NamePrefix1Code string

// May be one of DOCT, MADM, MISS, MIST, MIKS
type NamePrefix2Code string

type NaturalPersonIdentification1 struct {
	Id   Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id"`
	IdTp IdentificationType45Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 IdTp,omitempty"`
}

type NotificationGeneralInformation2 struct {
	NtfctnTp             NotificationType3Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NtfctnTp"`
	NtfctnSts            EventStatus1          `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NtfctnSts"`
	ShrhldrRghtsDrctvInd bool                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 ShrhldrRghtsDrctvInd,omitempty"`
}

// May be one of NEWM, REPL, RMDR
type NotificationType3Code string

type NotificationUpdate2 struct {
	PrvsNtfctnId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrvsNtfctnId"`
	RcnfrmInstrs bool      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 RcnfrmInstrs,omitempty"`
}

type NumberOrPercentage1Choice struct {
	ThrshldPctg float64 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 ThrshldPctg,omitempty"`
	ThrshldNb   float64 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 ThrshldNb,omitempty"`
}

type OtherIdentification1 struct {
	Id  Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id"`
	Sfx Max16Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Sfx,omitempty"`
	Tp  IdentificationSource3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Tp"`
}

type ParticipationMethod1 struct {
	PrtcptnMtd      ParticipationMethod1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrtcptnMtd"`
	IssrDdlnForVtng DateFormat58Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 IssrDdlnForVtng"`
}

type ParticipationMethod1Choice struct {
	Cd    VotingParticipationMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Cd,omitempty"`
	Prtry GenericIdentification30        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Prtry,omitempty"`
}

type PartyIdentification129Choice struct {
	AnyBIC   AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AnyBIC,omitempty"`
	PrtryId  GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrtryId,omitempty"`
	NmAndAdr NameAndAddress5         `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NmAndAdr,omitempty"`
	LEI      LEIIdentifier           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 LEI,omitempty"`
}

type PartyIdentification198Choice struct {
	NtlRegnNb Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NtlRegnNb,omitempty"`
	LEI       LEIIdentifier           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 LEI,omitempty"`
	AnyBIC    AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AnyBIC,omitempty"`
	ClntId    Max50Text               `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 ClntId,omitempty"`
	PrtryId   GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrtryId,omitempty"`
}

type PartyIdentification221 struct {
	NmAndAdr PersonName2                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NmAndAdr"`
	EmailAdr Max256Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EmailAdr,omitempty"`
	Id       PartyIdentification198Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id"`
}

type PartyIdentification224 struct {
	NmAndAdr PersonName2                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NmAndAdr"`
	EmailAdr Max256Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EmailAdr,omitempty"`
	Id       PartyIdentification198Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id,omitempty"`
}

type PartyIdentification231Choice struct {
	LglPrsn  PartyIdentification221   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 LglPrsn,omitempty"`
	NtrlPrsn []PartyIdentification238 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NtrlPrsn,omitempty"`
}

type PartyIdentification232Choice struct {
	LglPrsn  PartyIdentification221 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 LglPrsn,omitempty"`
	NtrlPrsn PartyIdentification238 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NtrlPrsn,omitempty"`
}

type PartyIdentification233Choice struct {
	LglPrsn  PartyIdentification224   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 LglPrsn,omitempty"`
	NtrlPrsn []PartyIdentification240 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NtrlPrsn,omitempty"`
}

type PartyIdentification238 struct {
	NmAndAdr        PersonName3                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NmAndAdr"`
	EmailAdr        Max256Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EmailAdr,omitempty"`
	Id              NaturalPersonIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id"`
	Ntlty           CountryCode                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Ntlty,omitempty"`
	DtAndPlcOfBirth DateAndPlaceOfBirth2         `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 DtAndPlcOfBirth,omitempty"`
}

type PartyIdentification240 struct {
	NmAndAdr        PersonName3                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NmAndAdr"`
	EmailAdr        Max256Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EmailAdr,omitempty"`
	Id              NaturalPersonIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id,omitempty"`
	Ntlty           CountryCode                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Ntlty,omitempty"`
	DtAndPlcOfBirth DateAndPlaceOfBirth2         `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 DtAndPlcOfBirth,omitempty"`
}

type PersonName2 struct {
	Nm  Max350Text      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Nm"`
	Adr PostalAddress26 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Adr,omitempty"`
}

type PersonName3 struct {
	NmPrfx NamePrefix2Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NmPrfx,omitempty"`
	FrstNm Max350Text      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 FrstNm"`
	Srnm   Max350Text      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Srnm"`
	Adr    PostalAddress26 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Adr,omitempty"`
}

// Must match the pattern \+[0-9]{1,3}-[0-9()+\-]{1,30}
type PhoneNumber string

// May be one of UKWN
type PlaceType1Code string

type PostalAddress1 struct {
	AdrTp       AddressType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AdrTp,omitempty"`
	AdrLine     []Max70Text      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AdrLine,omitempty"`
	StrtNm      Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 StrtNm,omitempty"`
	BldgNb      Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 BldgNb,omitempty"`
	PstCd       Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PstCd,omitempty"`
	TwnNm       Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 TwnNm,omitempty"`
	CtrySubDvsn Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 CtrySubDvsn,omitempty"`
	Ctry        CountryCode      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Ctry"`
}

type PostalAddress26 struct {
	AdrTp       AddressType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AdrTp,omitempty"`
	AdrLine     []Max70Text      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AdrLine,omitempty"`
	StrtNm      Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 StrtNm,omitempty"`
	BldgNb      Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 BldgNb,omitempty"`
	PstBx       Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PstBx,omitempty"`
	PstCd       Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PstCd,omitempty"`
	TwnNm       Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 TwnNm,omitempty"`
	CtrySubDvsn Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 CtrySubDvsn,omitempty"`
	Ctry        CountryCode      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Ctry"`
}

// May be one of NOTA, LOCA, APOS, COUN
type PowerOfAttorneyLegalisation1Code string

type PowerOfAttorneyRequirements4 struct {
	LglRqrmnt       []PowerOfAttorneyLegalisation1Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 LglRqrmnt,omitempty"`
	OthrDcmnttn     Max350Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 OthrDcmnttn,omitempty"`
	DocSubmissnDdln DateFormat58Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 DocSubmissnDdln,omitempty"`
}

type PriceRateOrAmount3Choice struct {
	Rate float64                                    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Rate,omitempty"`
	Amt  ActiveOrHistoricCurrencyAnd13DecimalAmount `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Amt,omitempty"`
}

// May be one of AFTE, WITH, BEFO, INFO
type ProcessingPosition3Code string

type Proxy4Choice struct {
	Prxy         ProxyAppointmentInformation5 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Prxy,omitempty"`
	PrxyNotAllwd ProxyNotAllowed1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrxyNotAllwd,omitempty"`
}

type Proxy9 struct {
	PrxyTp   ProxyType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrxyTp"`
	PrsnDtls IndividualPerson43 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrsnDtls,omitempty"`
}

type ProxyAppointmentInformation5 struct {
	RegnMtd     Max350Text         `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 RegnMtd,omitempty"`
	Ddln        DateFormat58Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Ddln,omitempty"`
	MktDdln     DateFormat58Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 MktDdln,omitempty"`
	AuthrsdPrxy []Proxy9           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AuthrsdPrxy,omitempty"`
}

// May be one of NPRO
type ProxyNotAllowed1Code string

// May be one of CHRM, DISC, HLDR
type ProxyType2Code string

type QuorumQuantity1Choice struct {
	QrmQty     Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 QrmQty,omitempty"`
	QrmQtyPctg float64   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 QrmQtyPctg,omitempty"`
}

type Resolution5 struct {
	IssrLabl                  Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 IssrLabl"`
	Desc                      []ItemDescription1        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Desc,omitempty"`
	ListgGrpRsltnLabl         Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 ListgGrpRsltnLabl,omitempty"`
	Tp                        ResolutionType2Code       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Tp,omitempty"`
	ForInfOnly                bool                      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 ForInfOnly"`
	VoteTp                    VoteType1Code             `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteTp,omitempty"`
	Sts                       ResolutionStatus1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Sts"`
	SubmittdBySctyHldr        bool                      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 SubmittdBySctyHldr,omitempty"`
	RghtToWdrwInd             bool                      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 RghtToWdrwInd,omitempty"`
	VoteInstrTp               []VoteInstructionType1    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteInstrTp,omitempty"`
	MgmtRcmmndtn              VoteInstruction5Code      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 MgmtRcmmndtn,omitempty"`
	NtifngPtyRcmmndtn         VoteInstruction5Code      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 NtifngPtyRcmmndtn,omitempty"`
	Entitlmnt                 Entitlement1Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Entitlmnt,omitempty"`
	VtngRghtsThrshldForApprvl NumberOrPercentage1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VtngRghtsThrshldForApprvl,omitempty"`
	URLAdr                    Max2048Text               `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 URLAdr,omitempty"`
}

// May be one of ACTV, WDRA
type ResolutionStatus1Code string

// May be one of EXTR, SPCL
type ResolutionType2Code string

// May be one of CUST, ICSD, NCSD, SHHE
type SafekeepingPlace1Code string

// May be one of SHHE, ALLP
type SafekeepingPlace2Code string

type SafekeepingPlaceFormat28Choice struct {
	Id      SafekeepingPlaceTypeAndText6           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id,omitempty"`
	Ctry    CountryCode                            `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Ctry,omitempty"`
	TpAndId SafekeepingPlaceTypeAndIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 TpAndId,omitempty"`
	Prtry   GenericIdentification78                `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Prtry,omitempty"`
}

type SafekeepingPlaceTypeAndIdentification1 struct {
	SfkpgPlcTp SafekeepingPlace1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 SfkpgPlcTp"`
	Id         AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id"`
}

type SafekeepingPlaceTypeAndText6 struct {
	SfkpgPlcTp SafekeepingPlace2Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 SfkpgPlcTp"`
	Id         Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Id,omitempty"`
}

// May be one of BLOK, ELIG, PEND, PENR, NOMI, SETD, BORR, LOAN, SPOS, TRAD, COLI, COLO, UNBA, INBA, REGO
type SecuritiesEntryType2Code string

type SecurityIdentification19 struct {
	ISIN   ISINOct2015Identifier  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 ISIN,omitempty"`
	OthrId []OtherIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 OthrId,omitempty"`
	Desc   Max140Text             `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Desc,omitempty"`
}

type SecurityPosition12 struct {
	FinInstrmId SecurityIdentification19 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 FinInstrmId"`
	Pos         []EligiblePosition9      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Pos,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

// May be one of ARNU, CUST, CORP, DRLC, IDCD, NRIN, CCPT, SOCS, TXID
type TypeOfIdentification4Code string

// May be one of ABST, CAGS, CHRM, CFOR, NOAC, WTHH, ONEY, THRY, TWOY, BLNK, NREC
type VoteInstruction5Code string

// May be one of ABST, CAGS, AMGT, BLNK, CHRM, DISC, CFOR, NOAC, ONEY, THRY, TWOY, WTHH, WMGT
type VoteInstruction6Code string

type VoteInstructionType1 struct {
	VoteInstrTpCd VoteInstructionType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteInstrTpCd"`
	AddtlInf      Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlInf,omitempty"`
}

type VoteInstructionType1Choice struct {
	Tp    VoteInstruction6Code    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Tp,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 Prtry,omitempty"`
}

type VoteMethods3 struct {
	VoteThrghNtwk []AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteThrghNtwk,omitempty"`
	VoteByMail    []PostalAddress1          `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteByMail,omitempty"`
	ElctrncVote   []CommunicationAddress11  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 ElctrncVote,omitempty"`
	VoteByTel     []Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteByTel,omitempty"`
}

type VoteParameters6 struct {
	SctiesQtyReqrdToVote FinancialInstrumentQuantity18Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 SctiesQtyReqrdToVote,omitempty"`
	PrtlVoteAllwd        bool                                `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrtlVoteAllwd"`
	SpltVoteAllwd        bool                                `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 SpltVoteAllwd"`
	VoteDdln             DateFormat58Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteDdln,omitempty"`
	VoteMktDdln          DateFormat58Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteMktDdln,omitempty"`
	VoteMthds            VoteMethods3                        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteMthds,omitempty"`
	VtngBlltElctrncAdr   CommunicationAddress11              `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VtngBlltElctrncAdr,omitempty"`
	VtngBlltReqAdr       PostalAddress1                      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VtngBlltReqAdr,omitempty"`
	RvcbltyDdln          DateFormat58Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 RvcbltyDdln,omitempty"`
	RvcbltyMktDdln       DateFormat58Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 RvcbltyMktDdln,omitempty"`
	BnfclOwnrDsclsr      bool                                `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 BnfclOwnrDsclsr,omitempty"`
	EarlyIncntivPrm      IncentivePremium5                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EarlyIncntivPrm,omitempty"`
	IncntivPrm           IncentivePremium5                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 IncntivPrm,omitempty"`
	EarlyVoteWthPrmDdln  DateFormat58Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 EarlyVoteWthPrmDdln,omitempty"`
	VoteWthPrmDdln       DateFormat58Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteWthPrmDdln,omitempty"`
	VoteWthPrmMktDdln    DateFormat58Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteWthPrmMktDdln,omitempty"`
	AddtlVtngRqrmnts     Max350Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 AddtlVtngRqrmnts,omitempty"`
	PrvsInstrInvldtyInd  bool                                `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 PrvsInstrInvldtyInd,omitempty"`
}

// May be one of ADVI, BNDG
type VoteType1Code string

type VoteTypeAndQuantity1 struct {
	VoteInstrTp VoteInstructionType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteInstrTp"`
	VoteQty     float64                    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.001.001.08 VoteQty"`
}

// May be one of MAIL, PHYS, PHNV, PRXY, VIRT, EVOT
type VotingParticipationMethod1Code string

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
